### ISSUE TITLE
Week, Hour, Minute and Second components

### ISSUE THREAD

**Issue by thoroc** [gpgkd906/date_component#3]
### Feature Request

Hi, I have done some work on a fork to add the following:

* Week component
* Hour component
* Minute component
* Second component

as well as changing the `interval_` available to the `duration`. That ofc is a breaking change.

I have also refactored the tests to be a tad more exhaustive.

I am unsure how to proceed with this, if you would consider it (BC), but the fork is available for now  at https://github.com/thoroc/date_component.

~thoroc

**Comment by gpgkd906** [comment]
@thoroc 
thank you for your work!
I had a minor surgery last month, sorry for the late reply.
> That ofc is a breaking change.

I am OK for this.
so please feel free to open the PR.
thank you for your work again!

**Comment by thoroc** [comment]
Hi,

Sorry to hear about your health issue. Hopefully it isn't too bad.

I have opened a draft pull request: https://github.com/gpgkd906/date_component/pull/4

Let me know if you need to see something else in there.

~thoroc

**Comment by gpgkd906** [comment]
@thoroc
Thank you for update the documentation！

I thought about the BC again, maybe we could make just a little adjustment
・keep the original day
・rename the new day based on the calculation of the week to **dayofweek**, or **daybyweek**
This will eliminates the BC
What do you think?

**Comment by thoroc** [comment]
That makes sense.

**Comment by thoroc** [comment]
merge PR.
